version: "2"
linters:
  enable:
    - bodyclose
    - copyloopvar
    - errorlint
    - iface
    - importas
    - loggercheck
    - mirror
    - misspell
    - nilnesserr
    - noctx
    - perfsprint
    - prealloc
    - recvcheck
    - revive
    - testifylint
    - unconvert
    - unparam
    - usestdlibvars
    - usetesting
    - wsl
  settings:
    govet:
      enable:
        - nilness
        - unusedwrite
    loggercheck:
      require-string-key: true
      no-printf-like: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
